# Generated by Django 3.0.2 on 2020-06-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=200)),
                ('a', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'log',
                'db_table': 'Chat_Log',
            },
        ),
    ]
