# Generated by Django 3.0.2 on 2020-06-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='질문')),
                ('answer', models.CharField(max_length=100, verbose_name='답')),
            ],
            options={
                'verbose_name': 'Qs',
                'verbose_name_plural': 'Qs',
                'db_table': 'questions',
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
